language: c

sudo: false

addons:
  apt:
    sources:
     - sourceline: 'deb https://dl.bintray.com/gob-backup/travis-deps trusty main'
    packages:
     - libsodium23
     - libsodium-dev
  coverity_scan:
    project:
      name: gob-backup/gob
      description: Block-based deduplicating backups
    notification_email: gob@pks.im
    build_command: make
    branch_pattern: coverity_scan

matrix:
 fast_finish: true
 include:
   - os: linux
     dist: trusty
     compiler: gcc
   - os: linux
     dist: trusty
     compiler: clang
     if: branch != coverity_scan
   - os: osx
     compiler: gcc
     if: branch != coverity_scan
   - os: osx
     compiler: clang
     if: branch != coverity_scan

install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then brew install libsodium; fi

script:
  - make
  - make test
  - PREFIX="${HOME}/dest" make install

branches:
 only:
   - master
   - coverity_scan
