language: c

addons:
  apt:
    packages:
     - python3-pip
  coverity_scan:
    project:
      name: gob-backup/gob
      description: Block-based deduplicating backups
    notification_email: gob@pks.im
    build_command: meson build && ninja -C build
    branch_pattern: coverity_scan

matrix:
 fast_finish: true
 include:
   - os: linux
     dist: xenial
     compiler: gcc
   - os: linux
     dist: xenial
     compiler: clang
     if: branch != coverity_scan
   - os: linux
     dist: bionic
     compiler: gcc
     if: branch != coverity_scan
   - os: linux
     dist: bionic
     compiler: clang
     if: branch != coverity_scan
   - os: osx
     compiler: gcc
     if: branch != coverity_scan
   - os: osx
     compiler: clang
     if: branch != coverity_scan

install:
  - |
    if test ${TRAVIS_OS_NAME} = "osx"
    then
        brew install meson
        wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-mac.zip
        unzip ninja-mac.zip
        mv ninja "${HOME}"/bin
    fi

    if test ${TRAVIS_OS_NAME} = "linux"
    then
        pip3 install --user 'meson<0.45.0'
        wget https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-linux.zip
        unzip ninja-linux.zip
        mv ninja "${HOME}"/bin
    fi

script:
  - meson build --prefix="${HOME}/dest"
  - ninja -C build test
  - ninja -C build install

branches:
 only:
   - master
   - coverity_scan
