language: c

dist: trusty
sudo: false

addons:
  apt:
    sources:
     - sourceline: 'deb https://dl.bintray.com/sb-backup/travis-deps trusty main'
    packages:
     - libsodium23
     - libsodium-dev

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then brew install libsodium; fi

script:
  - make
  - make test
  - PREFIX="${HOME}/dest" make install

branches:
 only:
   - master
