language: c

sudo: false

addons:
  apt:
    sources:
     - sourceline: 'deb https://dl.bintray.com/gob-backup/travis-deps trusty main'
    packages:
     - libsodium23
     - libsodium-dev

matrix:
 fast_finish: true
 include:
   - os: linux
     dist: trusty
     compiler: gcc
   - os: linux
     dist: trusty
     compiler: clang
   - os: osx
     compiler: gcc
   - os: osx
     compiler: clang

install:
  - if test ${TRAVIS_OS_NAME} = "osx"; then brew install libsodium; fi

script:
  - make
  - make test
  - PREFIX="${HOME}/dest" make install

branches:
 only:
   - master
