language: c

addons:
  apt:
    packages:
     - meson
     - ninja-build
    update: true
  homebrew:
    packages:
     - meson
     - ninja
    update: true
  coverity_scan:
    project:
      name: gob-backup/gob
      description: Block-based deduplicating backups
    notification_email: gob@pks.im
    build_command: meson build && ninja -C build
    branch_pattern: coverity_scan

matrix:
 fast_finish: true
 include:
   - os: linux
     dist: xenial
     compiler: gcc
   - os: linux
     dist: xenial
     compiler: clang
     if: branch != coverity_scan
   - os: linux
     dist: bionic
     compiler: gcc
     if: branch != coverity_scan
   - os: linux
     dist: bionic
     compiler: clang
     if: branch != coverity_scan
   - os: osx
     compiler: gcc
     if: branch != coverity_scan
   - os: osx
     compiler: clang
     if: branch != coverity_scan

script:
  - meson build --prefix="${HOME}/dest"
  - ninja -C build test
  - ninja -C build install

branches:
 only:
   - master
   - coverity_scan
